### ISSUE TITLE
dashstyle is missing in example configuration and documentation

### ISSUE THREAD

**Issue by emeins** [treban/pimatic-charts#2]
Error in pimatic-daemon.log after adding the example configuration:
Invalid config of device "testchart": Missing property "dashstyle" in /variables/0, Missing property "dashstyle" in /variables/1, Missing property "dashstyle" in /variables/2, Missing property "dashstyle" in /variables/3, Property "echo" is not a valid property

<dashstyle> coming with version 0.2 needs to be documented and added to config example doc.

I added
  ### "dashstyle": "Solid",
to variables configuration and it works fine.

**Comment by treban** [comment]
I have added this to the example
